apiVersion: apps/v1
kind: Deployment
metadata:
  name: cleanup
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cleanup
  template:
    metadata:
      labels:
        app: cleanup
    spec:
      containers:
      - name: cleanup
        image: mogalina/url-shortener:latest
        imagePullPolicy: Always
        command: ["python", "-m", "app.services.cleanup"]
        envFrom:
        - configMapRef:
            name: url-shortener-config
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
